# Generated by Django 4.1.5 on 2023-01-21 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('croaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Croak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiny_body', models.CharField(max_length=143)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='croaks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
